linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
  funlen:
    lines: 10
  nestif:
    min-complexity: 3
  dupl:
    threshold: 50
  maintidx:
    under: 20

linters:
  disable-all: true
  enable:
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - dupl
    - maintidx
